name: Build and Upload APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build unsigned Release APK
        run: ./gradlew assembleRelease

      - name: List APK files
        run: |
          echo "目录结构:"
          ls -R app/build/outputs/apk/
          
          # 检查是否存在 APK
          if [ -n "$(ls app/build/outputs/apk/release/*.apk 2>/dev/null)" ]; then
            echo "找到 APK 文件!"
          else
            echo "未找到 APK 文件!"
            exit 1
          fi

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: navboost-apk
          path: app/build/outputs/apk/release/*.apk
