name: Build and Upload APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:检出代码
        uses: actions/checkout@v4

      - name:设置JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name:赋予gradlew执行权限
        run: chmod +x gradlew

      - name:构建Release APK
        run: ./gradlew assembleRelease

      - name:列出APK文件
        run: |
          echo "目录结构:"
          ls -R app/build/outputs/apk/
          
          # 检查是否存在APK
          if [ -n "$(ls app/build/outputs/apk/release/*.apk 2>/dev/null)" ]; then
            echo "找到APK文件!"
          else
            echo "未找到APK文件!"
            exit 1
          fi

      - name:上传APK
        uses: actions/upload-artifact@v4
        with:
          name: navboost-apk
          path: app/build/outputs/apk/release/*.apk
